<?php

namespace IranKish\Contracts;

use IranKish\Enums\TransactionType;

/**
 * Contract for IranKish gateway implementation.
 *
 * This interface defines all public methods that a gateway implementation must expose.
 * Every method strictly follows the IranKish IPG Technical Guide V9.
 *
 * @link https://www.irankish.com/App_Data_Public/IPG/IPG_TechnicalGuide.V9.pdf
 */
interface GatewayContract
{
    /**
     * Request a payment token from IranKish.
     *
     * API Endpoint: /api/v3/tokenization/make
     *
     * This method is the entry point for initiating a transaction and retrieving the tokenIdentity
     * that must later be sent to the payment page.
     *
     * @param int $amount Total amount in Rials.
     * @param TransactionType|null $type Transaction type (defaults to Purchase).
     * @param array $options Optional fields accepted by IranKish tokenization API:
     *  - billInfo (string|null): Used for bill or special bill payments.
     *  - paymentId (string|null): Merchant’s internal order or payment reference ID.
     *  - requestId (string|null): Unique request identifier, max 20 chars. Auto-generated if not set.
     *  - requestTimestamp (int|null): Unix timestamp of the request. Default: current time().
     *  - revertUri (string|null): Callback URL where IranKish redirects after payment.
     *  - multiplexParameters (array|null): For split settlements. Each element must contain
     *      ['iban' => 'IRxxxx...', 'amount' => int]. Automatically processed by DigitalEnvelope.
     *  - additionalParameters (array|null): Optional metadata to pass to gateway.
     *  - cmsPreservationId (string|null): CMS transaction reference (if applicable).
     *  - asanShp (array|null): Used in AsanShp (Wallet) transactions.
     *  - isbehdadtransaction (bool|null): Flag for Behdad bank transactions.
     *
     * @return array{
     *   token: string|null,
     *   transactionType: string,
     *   raw: array
     * }
     *
     * @throws \IranKish\Exceptions\IranKishException
     *
     * @see https://www.irankish.com/App_Data_Public/IPG/IPG_TechnicalGuide.V9.pdf#page=16 (11.1 - Tokenization / Make)
     */
    public function requestToken(int $amount, ?TransactionType $type = null, array $options = []): array;

    /**
     * Request a "special" token for merchants with special contracts.
     *
     * Works identically to requestToken() but hits a different endpoint:
     * /api/v3/tokenization/makeSpecial
     *
     * Used for AsanShpWPP, IsacoWPP, and other white-label or partnership channels.
     *
     * @param int $amount Transaction amount in Rials.
     * @param TransactionType|null $type Transaction type (defaults to Purchase).
     * @param array $options Same as requestToken().
     *
     * @return array{
     *   token: string|null,
     *   transactionType: string,
     *   raw: array
     * }
     *
     * @throws \IranKish\Exceptions\IranKishException
     *
     * @see https://www.irankish.com/App_Data_Public/IPG/IPG_TechnicalGuide.V9.pdf#page=22 (11.1.2 - makeSpecial)
     */
    public function requestSpecialToken(int $amount, ?TransactionType $type = null, array $options = []): array;

    /**
     * Redirect user to the IranKish payment page using auto-submitted HTML form.
     *
     * This method outputs a POST form containing the tokenIdentity and immediately submits it.
     * Use when you want the package to handle redirection automatically.
     *
     * @param string $token TokenIdentity value returned by requestToken().
     *
     * @return void
     *
     * @see https://www.irankish.com/App_Data_Public/IPG/IPG_TechnicalGuide.V9.pdf#page=36 (Payment Form)
     */
    public function redirect(string $token): void;

    /**
     * Return redirection metadata instead of auto-submitting a form.
     *
     * Use when you want to handle redirection manually in your front-end or framework.
     *
     * @param string $token TokenIdentity value returned by requestToken().
     *
     * @return array{
     *   transactionUrl: string,
     *   token: string,
     *   method: string,
     *   fields: array
     * }
     *
     * @see https://www.irankish.com/App_Data_Public/IPG/IPG_TechnicalGuide.V9.pdf#page=36 (Payment Form)
     */
    public function redirectData(string $token): array;

    /**
     * Confirm (verify) a payment after the customer returns from IranKish gateway.
     *
     * API Endpoint: /api/v3/confirmation/purchase
     *
     * @param string $token TokenIdentity received in callback request.
     * @param string $rrn Retrieval Reference Number (RRN) — 12-digit unique reference generated by IranKish.
     * @param string $stan System Trace Audit Number (STAN) — 6-digit transaction trace number.
     *
     * @return array Raw JSON response from IranKish confirmation endpoint.
     *
     * @throws \IranKish\Exceptions\IranKishException
     *
     * @see https://www.irankish.com/App_Data_Public/IPG/IPG_TechnicalGuide.V9.pdf#page=30 (11.2 - Confirmation / Purchase)
     */
    public function confirm(string $token, string $rrn, string $stan): array;

    /**
     * Reverse (void) a previously successful purchase.
     *
     * API Endpoint: /api/v3/confirmation/reversePurchase
     * Must be executed before daily settlement cutoff time.
     *
     * @param string $token TokenIdentity used in the original transaction.
     * @param string $rrn Retrieval Reference Number (RRN).
     * @param string $stan System Trace Audit Number (STAN).
     *
     * @return array Raw JSON response from IranKish reverse endpoint.
     *
     * @throws \IranKish\Exceptions\IranKishException
     *
     * @see https://www.irankish.com/App_Data_Public/IPG/IPG_TechnicalGuide.V9.pdf#page=34 (11.4 - Reverse Purchase)
     */
    public function reverse(string $token, string $rrn, string $stan): array;

    /**
     * Inquiry (verify) a transaction status up to 7 days after the operation.
     *
     * API Endpoint: /api/v3/inquiry/single
     *
     * @param array $criteria The inquiry criteria:
     *  - passPhrase (string|null): Optional password; defaults to config('irankish.password').
     *  - terminalId (string|null): Optional terminal ID; defaults to config('irankish.terminal_id').
     *  - findOption (int): Required (1 = by RRN, 2 = by tokenIdentity, 3 = by requestId).
     *  - retrievalReferenceNumber (string|null): Required if findOption=1.
     *  - tokenIdentity (string|null): Required if findOption=2.
     *  - requestId (string|null): Required if findOption=3.
     *
     * @return array Raw JSON response from IranKish inquiry endpoint.
     *
     * @throws \IranKish\Exceptions\IranKishException
     *
     * @see https://www.irankish.com/App_Data_Public/IPG/IPG_TechnicalGuide.V9.pdf#page=37 (11.6 - Inquiry / Single)
     */
    public function inquiry(array $criteria): array;
}
